pipeline {
    agent any

    tools {
        maven 'maven3'
    }

    environment {
        JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64'
        PATH = "${env.JAVA_HOME}/bin:${env.PATH}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/SamirP33/spring-petclinic.git'
            }
        }

        stage('Build Application') {
            steps {
                sh '''
                echo "Using Java version:"
                java -version

                echo "Building project using Maven..."
                mvn clean install -DskipTests
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    sh '''
                    echo "Running SonarQube analysis..."
                    mvn sonar:sonar
                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                echo "Building Docker image..."
                docker build -t samirp33/petclinic-app .
                '''
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                    echo "Logging into Docker Hub..."
                    echo $PASS | docker login -u $USER --password-stdin

                    echo "Pushing Docker image..."
                    docker push samirp33/petclinic-app
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check logs.'
        }
    }
}
