# -*- coding: utf-8 -*-
"""Backup-File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OmnxEM8oGIQVgaA1zYcoHDgusNafdGVe
"""

print("Hello Wolrd")

import shutil
import datetime
import os

def backup_files(source, destination):
    today = datetime.date.today()
    backup_file_name = os.path.join(destination, f"backup_{today}")
    shutil.make_archive(backup_file_name, 'gztar', source)

source = "/path/to/source_folder"
destination = "/path/to/backup_folder"

backup_files(source, destination)